[project]
name = "python-fastmcp"
version = "0.1.0"
description = "Python Fastmcp samples and tutorials"
readme = "README.md"
authors = [
    { name = "Ravi Pandya", email = "ravipandya1229@gmail.com" }
]
requires-python = ">=3.14.4"
dependencies = [
    "fastmcp[apps]>=4.0.9",
]

[project.scripts]
python-fastmcp = "python_fastmcp:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
